name: Configure CloudFormation linting
on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

inputs:
  path:
  

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
