name: Configure CloudFormation linting
on:
  workflow_call:
  workflow_dispatch:
    inputs:
      path:
        description: "Path/files to scan (space seperated) that contain all yml files."
        required: true
        default: '*.yml *.yaml'
        
permissions:
  contents: read

jobs:
  lint:
    name: "Lint CloudFormation files"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - name: Setup cfn-lint
      run: |
        python -m pip install cfn-lint
    - name: Run cfn-lint
      run: |
        cfn-lint --version
        cfn-lint ${{ github.event.inputs.path }}
